### ISSUE TITLE
File Duplication Not Handled

### ISSUE THREAD

**Issue by devonsydney** [tsvetann/medusa-file-bunny#3]
There is no error-handling for uniqueness of files. The official S3 plugin from medusa uses UID's in the filename:
* filename: file.jpg
* uploaded as: file-1683225940306.jpg

This ensures if files with the same name are uploaded (a common usage pattern) they will not be conflicted or overwritten.

**Comment by tsvetann** [comment]
@devonsydney thanks for your ticket. Lets make this optional via config

**Comment by tsvetann** [comment]
resolved
